// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfEV8ZtQ8HTENWyFqUhviwnm3HEnpvCiU',
    appId: '1:899298320388:web:4616ad360f41c7bc591551',
    messagingSenderId: '899298320388',
    projectId: 'betatestingtask',
    authDomain: 'betatestingtask.firebaseapp.com',
    storageBucket: 'betatestingtask.firebasestorage.app',
    measurementId: 'G-1XH899JJWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ndCYLtKaiJVLq4yVdhXpZcIM70JGLV8',
    appId: '1:899298320388:android:3605ef5c8a573cf4591551',
    messagingSenderId: '899298320388',
    projectId: 'betatestingtask',
    storageBucket: 'betatestingtask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb9Cw10vukS8sxCw4EUay3WEnzlj6iQak',
    appId: '1:899298320388:ios:711d21d78d1f07d0591551',
    messagingSenderId: '899298320388',
    projectId: 'betatestingtask',
    storageBucket: 'betatestingtask.firebasestorage.app',
    iosBundleId: 'com.example.cleanArcticture',
  );
}
